### ISSUE TITLE
Leverage Checklist for Calypso

### ISSUE THREAD

**Issue by toteki** [umee-network/umee#1315]
Features (Fast PRs)
- #1093 
- #1162 
- #1163
- #1227
- #1166 
- #944 
- #1205 
- #1223 

Action possibly required
- #827
- #1324 

### QA tests 

description: https://www.notion.so/QA-Chain-Crash-Tests-6ef51a210fcc41b4980a74e58166d1f0
- [ ] https://github.com/umee-network/umee/issues/1207
- [ ] https://github.com/umee-network/umee/issues/1208
- [ ] https://github.com/umee-network/umee/issues/1210
- [ ] https://github.com/umee-network/umee/issues/1209

### Investigate during beta
- #831
- #1316
