### ISSUE TITLE
x/leverage: Tracking Issue

### ISSUE THREAD

**Issue by alexanderbez** [umee-network/umee#142]
A rough list of functional items that need to be completed for Umee's leveraging functionality to be considered "complete":

- [x] The `x/leverage` module should contain a registry of supported tokens for users to borrow and lend
- [x] The `x/leverage` module should be able to get price information of all tokens in the token registry via a price feed oracle
- [x] A user should be able to lend a token that exists in the registry of allowed tokens
- [x] A user should be able to enable or disable a lent token as collateral that contributes to the user's total borrowing power so long as that token is enabled to be used as collateral by the `x/leverage` module
- [x] A user should be able to borrow a token from the registry of allowed tokens up to their total borrowing power
- [ ] A user should accrue LP incentives for both borrowing and lending
- [x] A user should be able to reclaim their lent tokens along with any interest and LP incentives accrued
- [x] A user should be able to repay their borrow position along with any interest accrued
- [x] Stakeholders should be able to update the token registry via governance

----

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
The only thing missing here is LP incentives, which we can track in a separate issue. Closing this 👍
