### ISSUE TITLE
Epic: Price feeder v2

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#1470]
## Summary

Epic to track Price Feeder V2 tickets, emphasizing asset support and debugging.

Closes #1470

- [x] #1305
- [x] #792
- [x] https://github.com/umee-network/osmosis-api/issues/43
- [x] https://github.com/umee-network/osmosis-api/issues/42
- [x] https://github.com/umee-network/osmosis-api/issues/41
- [x] #1263 
- [x] #1380
- [x] #1467
- [x] #1507
- [x] #1584

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adamewozniak** [comment]
I'm keeping this open for now even though all these tasks are through, since releasing price feeder v2.0.0 is dependent on https://github.com/umee-network/umee/issues/1521

**Comment by adamewozniak** [comment]
Closing since we released this anyways as a part of the last asset update :^)
