### ISSUE TITLE
Epic: Price Feeder low cap asset support

### ISSUE THREAD

**Issue by rbajollari** [umee-network/umee#1760]
## Summary
We need to test and make sure the Price Feeder can support these assets: 
`ATOM` | `UMEE` | `AXL-USDC` | `ETH` | `BTC` | `DAI` | `CRO` | `BNB` | `stATOM` | `stOSMO` | `OSMO` | `IST` | `JUNO` | `HUAHUA`

- [ ] #1757 
- [ ] #1758
- [ ] #1759  

## Proposal

---

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
