### ISSUE TITLE
the oracle is accepting exchange rates that are not in the accept list

### ISSUE THREAD

**Issue by adamewozniak** [umee-network/umee#413]
## Summary of Bug

Right now the x/oracle module is accepting votes for exchange rates that are not in the accept list. We should : 

- [x] 1. Update the price feeder to make sure we're filtering out any coins in the config that are not in the accept list #421
- [x] 2. Drop votes for exchange rates not in the accept list (note that we should not drop the `AggregateExchangeRateVote` altogether, in the case that validators update their configs for a new exchange rate before that rate gets added to `AcceptList`) #418
- [x] 3. Add some tests #418 & #421

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
